### ISSUE TITLE
minor in-game

### ISSUE THREAD

**Issue by ClassyH** [berendbro/CookiesRulezzzExpert#1]
**Describe the bug**
crimson portals van thaumcraft branden overdag

**To Reproduce**
/ ze branden, getest in singleplayer

**Expected behavior**
crimson portals mogen niet branden want nu zijn er gewoon geen in de wereld om te gebruiken voor thaumcraft

**Screenshots**
zijn er geen dus kan geen ss nemen

**Additional context**
komt door de nieuwe mobswarm mod die alle mobs laat branden overdag

**Comment by Dzetacq** [comment]
Ik stem voor mobs niet laten branden! 😈

**Comment by berendbro** [comment]
ah, i've seen this in the config files, i'll fix it right now

**Comment by berendbro** [comment]
turned it off in the config, swarming mobs will no longer burn in daylight
